// <auto-generated />
using System;
using AnFoodAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnFoodAPI.Migrations
{
    [DbContext(typeof(AnshopDbContext))]
    [Migration("20260210151753_ThemBangChiTietKho")]
    partial class ThemBangChiTietKho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("AnFoodAPI.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_chi_tiet");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("don_gia");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("gia_ban");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_don_hang");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_mon");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int(11)")
                        .HasColumnName("so_luong");

                    b.HasKey("MaChiTiet")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaDonHang" }, "ma_don_hang");

                    b.HasIndex(new[] { "MaMon" }, "ma_mon");

                    b.ToTable("chi_tiet_don_hang", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaChiTietGio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_chi_tiet");

                    b.Property<int?>("MaGioHang")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_gio_hang");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_mon");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int(11)")
                        .HasColumnName("so_luong");

                    b.HasKey("MaChiTietGio")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaGioHang" }, "ma_gio_hang");

                    b.HasIndex(new[] { "MaMon" }, "ma_mon")
                        .HasDatabaseName("ma_mon1");

                    b.ToTable("chi_tiet_gio_hang", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_danh_gia");

                    b.Property<int>("MaMon")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_mon");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_danh_gia")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("NhanXet")
                        .HasColumnType("text")
                        .HasColumnName("nhan_xet");

                    b.Property<int>("SoSao")
                        .HasColumnType("int(11)")
                        .HasColumnName("so_sao");

                    b.HasKey("MaDanhGia")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaMon" }, "ma_mon")
                        .HasDatabaseName("ma_mon2");

                    b.HasIndex(new[] { "MaNguoiDung" }, "ma_nguoi_dung");

                    b.ToTable("danh_gia", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_danh_muc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ten_danh_muc");

                    b.HasKey("MaDanhMuc")
                        .HasName("PRIMARY");

                    b.ToTable("danh_muc", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.DiaChiGiaoHang", b =>
                {
                    b.Property<int>("MaDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_dia_chi");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi");

                    b.Property<string>("HoTenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ho_ten_nguoi_nhan");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<bool>("MacDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("mac_dinh")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.HasKey("MaDiaChi")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaNguoiDung" }, "ma_nguoi_dung")
                        .HasDatabaseName("ma_nguoi_dung1");

                    b.ToTable("dia_chi_giao_hang", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_don_hang");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi_giao_hang");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<int?>("MaDiaChi")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_dia_chi");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_dat")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("NguoiNhan")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nguoi_nhan");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<decimal?>("TongTien")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .HasColumnType("enum('cho_xu_ly','dang_giao','hoan_thanh','huy','ChoDuyet')")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDonHang")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaDiaChi" }, "ma_dia_chi");

                    b.HasIndex(new[] { "MaNguoiDung" }, "ma_nguoi_dung")
                        .HasDatabaseName("ma_nguoi_dung2");

                    b.ToTable("don_hang", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_gio_hang");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("MaGioHang")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaNguoiDung" }, "ma_nguoi_dung")
                        .HasDatabaseName("ma_nguoi_dung3");

                    b.ToTable("gio_hang", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.GoiYAi", b =>
                {
                    b.Property<int>("MaGoiY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_goi_y");

                    b.Property<float?>("Diem")
                        .HasColumnType("float")
                        .HasColumnName("diem");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_mon");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("MaGoiY")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaMon" }, "ma_mon")
                        .HasDatabaseName("ma_mon3");

                    b.HasIndex(new[] { "MaNguoiDung" }, "ma_nguoi_dung")
                        .HasDatabaseName("ma_nguoi_dung4");

                    b.ToTable("goi_y_ai", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.HanhViNguoiDung", b =>
                {
                    b.Property<int>("MaHanhVi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_hanh_vi");

                    b.Property<string>("HanhVi")
                        .HasColumnType("enum('xem','them_gio','mua')")
                        .HasColumnName("hanh_vi");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_mon");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("MaHanhVi")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaMon" }, "ma_mon")
                        .HasDatabaseName("ma_mon4");

                    b.HasIndex(new[] { "MaNguoiDung" }, "ma_nguoi_dung")
                        .HasDatabaseName("ma_nguoi_dung5");

                    b.ToTable("hanh_vi_nguoi_dung", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.HinhAnhMonAn", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hinh");

                    b.Property<string>("DuongDan")
                        .HasColumnType("longtext")
                        .HasColumnName("duong_dan");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_mon");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaMon");

                    b.ToTable("hinh_anh_mon_an", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.LichSuKho", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_lich_su");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("LoaiGiaoDich")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("loai_giao_dich");

                    b.Property<int>("MaMon")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_mon");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<int>("SoLuongTonSauKhiDoi")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_ton_sau_khi_doi");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaMon");

                    b.ToTable("lich_su_kho");
                });

            modelBuilder.Entity("AnFoodAPI.Models.LichSuTrangThaiDonHang", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_lich_su");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_don_hang");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaLichSu")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaDonHang" }, "ma_don_hang")
                        .HasDatabaseName("ma_don_hang1");

                    b.ToTable("lich_su_trang_thai_don_hang", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.LienHe", b =>
                {
                    b.Property<int>("MaLienHe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_lien_he");

                    b.Property<bool?>("DaPhanHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("da_phan_hoi")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<DateTime?>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_gui")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text")
                        .HasColumnName("noi_dung");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.HasKey("MaLienHe")
                        .HasName("PRIMARY");

                    b.ToTable("lien_he", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.MonAn", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_mon");

                    b.Property<int?>("BanChay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ban_chay")
                        .HasDefaultValueSql("'0'");

                    b.Property<decimal>("Gia")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("gia");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("longtext")
                        .HasColumnName("hinh_anh");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("LaDoUongMat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("la_do_uong_mat")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("LaMonNong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("la_mon_nong")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_danh_muc");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<string>("TenMon")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ten_mon");

                    b.Property<int?>("TonKho")
                        .HasColumnType("int(11)")
                        .HasColumnName("ton_kho");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('con_ban','het_hang')")
                        .HasColumnName("trang_thai")
                        .HasDefaultValueSql("'con_ban'");

                    b.HasKey("MaMon")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaDanhMuc" }, "ma_danh_muc");

                    b.ToTable("mon_an", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaVaiTro")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_vai_tro");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("OtpCode")
                        .HasColumnType("longtext")
                        .HasColumnName("otp_code");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("otp_expiry");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('hoat_dong','khoa')")
                        .HasColumnName("trang_thai")
                        .HasDefaultValueSql("'hoat_dong'");

                    b.HasKey("MaNguoiDung")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "MaVaiTro" }, "ma_vai_tro");

                    b.ToTable("nguoi_dung", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.QuangCao", b =>
                {
                    b.Property<int>("MaQuangCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_quang_cao");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("longtext")
                        .HasColumnName("hinh_anh");

                    b.Property<bool>("KichHoat")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("kich_hoat");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("ma_danh_muc");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("int")
                        .HasColumnName("phan_tram_giam");

                    b.Property<string>("TieuDe")
                        .HasColumnType("longtext")
                        .HasColumnName("tieu_de");

                    b.HasKey("MaQuangCao");

                    b.ToTable("quang_cao");
                });

            modelBuilder.Entity("AnFoodAPI.Models.QuyTacThoiGian", b =>
                {
                    b.Property<int>("MaQuyTac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_quy_tac");

                    b.Property<string>("Buoi")
                        .HasColumnType("enum('sang','trua','toi')")
                        .HasColumnName("buoi");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_danh_muc");

                    b.HasKey("MaQuyTac")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaDanhMuc" }, "ma_danh_muc")
                        .HasDatabaseName("ma_danh_muc1");

                    b.ToTable("quy_tac_thoi_gian", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_quyen");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("TenQuyen")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ten_quyen");

                    b.HasKey("MaQuyen")
                        .HasName("PRIMARY");

                    b.ToTable("quyen", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_thanh_toan");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_don_hang");

                    b.Property<DateTime>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_thanh_toan")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phuong_thuc");

                    b.Property<double>("SoTien")
                        .HasPrecision(10, 2)
                        .HasColumnType("double")
                        .HasColumnName("so_tien");

                    b.Property<string>("TrangThai")
                        .HasColumnType("enum('cho','da_thanh_toan','that_bai')")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaThanhToan")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaDonHang" }, "ma_don_hang")
                        .HasDatabaseName("ma_don_hang2");

                    b.ToTable("thanh_toan", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.ThoiTiet", b =>
                {
                    b.Property<int>("MaThoiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_thoi_tiet");

                    b.Property<string>("Loai")
                        .HasColumnType("enum('nong','lanh','mua')")
                        .HasColumnName("loai");

                    b.Property<float?>("NhietDo")
                        .HasColumnType("float")
                        .HasColumnName("nhiet_do");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("MaThoiTiet")
                        .HasName("PRIMARY");

                    b.ToTable("thoi_tiet", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_thong_bao");

                    b.Property<bool?>("DaDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("da_doc")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text")
                        .HasColumnName("noi_dung");

                    b.HasKey("MaThongBao")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaNguoiDung" }, "ma_nguoi_dung")
                        .HasDatabaseName("ma_nguoi_dung6");

                    b.ToTable("thong_bao", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_vai_tro");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("TenVaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ten_vai_tro");

                    b.HasKey("MaVaiTro")
                        .HasName("PRIMARY");

                    b.ToTable("vai_tro", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.YeuThich", b =>
                {
                    b.Property<int>("MaYeuThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_yeu_thich");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_mon");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("MaYeuThich")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaMon" }, "ma_mon")
                        .HasDatabaseName("ma_mon5");

                    b.HasIndex(new[] { "MaNguoiDung" }, "ma_nguoi_dung")
                        .HasDatabaseName("ma_nguoi_dung7");

                    b.ToTable("yeu_thich", (string)null);
                });

            modelBuilder.Entity("VaiTroQuyen", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_vai_tro");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int(11)")
                        .HasColumnName("ma_quyen");

                    b.HasKey("MaVaiTro", "MaQuyen")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "MaQuyen" }, "ma_quyen");

                    b.ToTable("vai_tro_quyen", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("AnFoodAPI.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang");

                    b.HasOne("AnFoodAPI.Models.MonAn", "MonAn")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaMon");

                    b.Navigation("DonHang");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("AnFoodAPI.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("AnFoodAPI.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang");

                    b.HasOne("AnFoodAPI.Models.MonAn", "MonAn")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaMon");

                    b.Navigation("GioHang");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("AnFoodAPI.Models.DanhGia", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", null)
                        .WithMany("DanhGia")
                        .HasForeignKey("MaMon")
                        .IsRequired();

                    b.HasOne("AnFoodAPI.Models.NguoiDung", null)
                        .WithMany("DanhGia")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired();
                });

            modelBuilder.Entity("AnFoodAPI.Models.DiaChiGiaoHang", b =>
                {
                    b.HasOne("AnFoodAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DiaChiGiaoHangs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("dia_chi_giao_hang_ibfk_1");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.DonHang", b =>
                {
                    b.HasOne("AnFoodAPI.Models.DiaChiGiaoHang", "DiaChiGiaoHangNavigation")
                        .WithMany()
                        .HasForeignKey("MaDiaChi");

                    b.HasOne("AnFoodAPI.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNguoiDung");

                    b.Navigation("DiaChiGiaoHangNavigation");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("AnFoodAPI.Models.GioHang", b =>
                {
                    b.HasOne("AnFoodAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("gio_hang_ibfk_1");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.GoiYAi", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", "MaMonNavigation")
                        .WithMany("GoiYAis")
                        .HasForeignKey("MaMon")
                        .HasConstraintName("goi_y_ai_ibfk_2");

                    b.HasOne("AnFoodAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("GoiYAis")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("goi_y_ai_ibfk_1");

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.HanhViNguoiDung", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", "MaMonNavigation")
                        .WithMany("HanhViNguoiDungs")
                        .HasForeignKey("MaMon")
                        .HasConstraintName("hanh_vi_nguoi_dung_ibfk_2");

                    b.HasOne("AnFoodAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("HanhViNguoiDungs")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("hanh_vi_nguoi_dung_ibfk_1");

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.HinhAnhMonAn", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", "MonAn")
                        .WithMany("HinhAnhMonAns")
                        .HasForeignKey("MaMon");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("AnFoodAPI.Models.LichSuKho", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("AnFoodAPI.Models.LichSuTrangThaiDonHang", b =>
                {
                    b.HasOne("AnFoodAPI.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("LichSuTrangThaiDonHangs")
                        .HasForeignKey("MaDonHang")
                        .HasConstraintName("lich_su_trang_thai_don_hang_ibfk_1");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.MonAn", b =>
                {
                    b.HasOne("AnFoodAPI.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("MonAns")
                        .HasForeignKey("MaDanhMuc")
                        .HasConstraintName("mon_an_ibfk_1");

                    b.Navigation("MaDanhMucNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.NguoiDung", b =>
                {
                    b.HasOne("AnFoodAPI.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .HasConstraintName("nguoi_dung_ibfk_1");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.QuyTacThoiGian", b =>
                {
                    b.HasOne("AnFoodAPI.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("QuyTacThoiGians")
                        .HasForeignKey("MaDanhMuc")
                        .HasConstraintName("quy_tac_thoi_gian_ibfk_1");

                    b.Navigation("MaDanhMucNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.ThanhToan", b =>
                {
                    b.HasOne("AnFoodAPI.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("thanh_toan_ibfk_1");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.ThongBao", b =>
                {
                    b.HasOne("AnFoodAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("thong_bao_ibfk_1");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.YeuThich", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", "MaMonNavigation")
                        .WithMany("YeuThiches")
                        .HasForeignKey("MaMon")
                        .HasConstraintName("yeu_thich_ibfk_2");

                    b.HasOne("AnFoodAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("YeuThiches")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("yeu_thich_ibfk_1");

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("VaiTroQuyen", b =>
                {
                    b.HasOne("AnFoodAPI.Models.Quyen", null)
                        .WithMany()
                        .HasForeignKey("MaQuyen")
                        .IsRequired()
                        .HasConstraintName("vai_tro_quyen_ibfk_2");

                    b.HasOne("AnFoodAPI.Models.VaiTro", null)
                        .WithMany()
                        .HasForeignKey("MaVaiTro")
                        .IsRequired()
                        .HasConstraintName("vai_tro_quyen_ibfk_1");
                });

            modelBuilder.Entity("AnFoodAPI.Models.DanhMuc", b =>
                {
                    b.Navigation("MonAns");

                    b.Navigation("QuyTacThoiGians");
                });

            modelBuilder.Entity("AnFoodAPI.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("LichSuTrangThaiDonHangs");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("AnFoodAPI.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("AnFoodAPI.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("DanhGia");

                    b.Navigation("GoiYAis");

                    b.Navigation("HanhViNguoiDungs");

                    b.Navigation("HinhAnhMonAns");

                    b.Navigation("YeuThiches");
                });

            modelBuilder.Entity("AnFoodAPI.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("DiaChiGiaoHangs");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");

                    b.Navigation("GoiYAis");

                    b.Navigation("HanhViNguoiDungs");

                    b.Navigation("ThongBaos");

                    b.Navigation("YeuThiches");
                });

            modelBuilder.Entity("AnFoodAPI.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
