// <auto-generated />
using System;
using AnFoodAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnFoodAPI.Migrations
{
    [DbContext(typeof(AnshopDbContext))]
    [Migration("20260703092324_UpdateLengthTrangThai")]
    partial class UpdateLengthTrangThai
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("AnFoodAPI.Models.AiLichSuHanhVi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<float>("DiemHanhVi")
                        .HasColumnType("float")
                        .HasColumnName("diem_hanh_vi");

                    b.Property<string>("LoaiHanhVi")
                        .HasColumnType("longtext")
                        .HasColumnName("loai_hanh_vi");

                    b.Property<int>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.HasKey("Id");

                    b.ToTable("ai_lich_su_hanh_vi");
                });

            modelBuilder.Entity("AnFoodAPI.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_chi_tiet");

                    b.Property<decimal?>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("don_gia");

                    b.Property<decimal?>("GiaBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_ban");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_don_hang");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.HasKey("MaChiTiet")
                        .HasName("PRIMARY");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaMon");

                    b.ToTable("chi_tiet_don_hang", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaChiTietGio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_chi_tiet");

                    b.Property<int?>("MaGioHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_gio_hang");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.HasKey("MaChiTietGio")
                        .HasName("PRIMARY");

                    b.HasIndex("MaGioHang");

                    b.HasIndex("MaMon");

                    b.ToTable("chi_tiet_gio_hang", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.ChiTietKho", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_chi_tiet");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<int>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_het_han");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_nhap");

                    b.Property<int?>("SoLuongHienTai")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_hien_tai");

                    b.Property<int?>("SoLuongNhap")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_nhap");

                    b.HasKey("MaChiTiet")
                        .HasName("PRIMARY");

                    b.HasIndex("MaMon");

                    b.ToTable("chi_tiet_kho", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.ChiTietPhieuKho", b =>
                {
                    b.Property<int>("MaChiTietPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_chi_tiet_phieu");

                    b.Property<decimal?>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("don_gia");

                    b.Property<int>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<int>("MaPhieu")
                        .HasColumnType("int")
                        .HasColumnName("ma_phieu");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.HasKey("MaChiTietPhieu")
                        .HasName("PRIMARY");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaPhieu");

                    b.ToTable("chi_tiet_phieu_kho", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_danh_gia");

                    b.Property<int>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_danh_gia")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("NhanXet")
                        .HasColumnType("longtext")
                        .HasColumnName("nhan_xet");

                    b.Property<int>("SoSao")
                        .HasColumnType("int")
                        .HasColumnName("so_sao");

                    b.HasKey("MaDanhGia")
                        .HasName("PRIMARY");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("danh_gia", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_danh_muc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenDanhMuc")
                        .HasColumnType("longtext")
                        .HasColumnName("ten_danh_muc");

                    b.HasKey("MaDanhMuc")
                        .HasName("PRIMARY");

                    b.ToTable("danh_muc", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.DiaChiGiaoHang", b =>
                {
                    b.Property<int>("MaDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_dia_chi");

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext")
                        .HasColumnName("dia_chi");

                    b.Property<string>("HoTenNguoiNhan")
                        .HasColumnType("longtext")
                        .HasColumnName("ho_ten_nguoi_nhan");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<bool>("MacDinh")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("mac_dinh");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext")
                        .HasColumnName("so_dien_thoai");

                    b.HasKey("MaDiaChi")
                        .HasName("PRIMARY");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("dia_chi_giao_hang", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_don_hang");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("longtext")
                        .HasColumnName("dia_chi_giao_hang");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("LyDoHuy")
                        .HasColumnType("longtext")
                        .HasColumnName("ly_do_huy");

                    b.Property<int?>("MaDiaChi")
                        .HasColumnType("int")
                        .HasColumnName("ma_dia_chi");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<int?>("MaVoucher")
                        .HasColumnType("int")
                        .HasColumnName("ma_voucher");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_dat")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("NguoiNhan")
                        .HasColumnType("longtext")
                        .HasColumnName("nguoi_nhan");

                    b.Property<decimal?>("PhiVanChuyen")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("phi_van_chuyen");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext")
                        .HasColumnName("so_dien_thoai");

                    b.Property<decimal?>("SoTienGiam")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("so_tien_giam");

                    b.Property<decimal?>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDonHang")
                        .HasName("PRIMARY");

                    b.HasIndex("MaDiaChi");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("don_hang", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_gio_hang");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao");

                    b.HasKey("MaGioHang")
                        .HasName("PRIMARY");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("gio_hang", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.GoiYAi", b =>
                {
                    b.Property<int>("MaGoiY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_goi_y");

                    b.Property<float?>("Diem")
                        .HasColumnType("float")
                        .HasColumnName("diem");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian");

                    b.HasKey("MaGoiY")
                        .HasName("PRIMARY");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("goi_y_ai", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.HanhViNguoiDung", b =>
                {
                    b.Property<int>("MaHanhVi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hanh_vi");

                    b.Property<string>("HanhVi")
                        .HasColumnType("longtext")
                        .HasColumnName("hanh_vi");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("MaHanhVi")
                        .HasName("PRIMARY");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("hanh_vi_nguoi_dung", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.HinhAnhMonAn", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hinh");

                    b.Property<string>("DuongDan")
                        .HasColumnType("longtext")
                        .HasColumnName("duong_dan");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.HasKey("MaHinhAnh")
                        .HasName("PRIMARY");

                    b.HasIndex("MaMon");

                    b.ToTable("hinh_anh_mon_an", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.LichSuChat", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTinNhan");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiDung");

                    b.Property<string>("NguoiGui")
                        .HasColumnType("longtext")
                        .HasColumnName("NguoiGui");

                    b.Property<string>("NoiDung")
                        .HasColumnType("longtext")
                        .HasColumnName("NoiDung");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ThoiGian");

                    b.HasKey("MaTinNhan");

                    b.ToTable("lich_su_chats");
                });

            modelBuilder.Entity("AnFoodAPI.Models.LichSuKho", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_lich_su");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("LoaiGiaoDich")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("loai_giao_dich");

                    b.Property<int>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<int>("SoLuongTonSauKhiDoi")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_ton_sau_khi_doi");

                    b.HasKey("MaLichSu")
                        .HasName("PRIMARY");

                    b.HasIndex("MaMon");

                    b.ToTable("lich_su_kho", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.LichSuTrangThaiDonHang", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_lich_su");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_don_hang");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaLichSu")
                        .HasName("PRIMARY");

                    b.HasIndex("MaDonHang");

                    b.ToTable("lich_su_trang_thai_don_hang", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.LienHe", b =>
                {
                    b.Property<int>("MaLienHe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_lien_he");

                    b.Property<bool?>("DaPhanHoi")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("da_phan_hoi");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .HasColumnType("longtext")
                        .HasColumnName("ho_ten");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_gui");

                    b.Property<string>("NoiDung")
                        .HasColumnType("longtext")
                        .HasColumnName("noi_dung");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext")
                        .HasColumnName("so_dien_thoai");

                    b.HasKey("MaLienHe")
                        .HasName("PRIMARY");

                    b.ToTable("lien_he", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.MonAn", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<int?>("BanChay")
                        .HasColumnType("int")
                        .HasColumnName("ban_chay");

                    b.Property<int?>("DaBan")
                        .HasColumnType("int")
                        .HasColumnName("da_ban");

                    b.Property<decimal?>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gia");

                    b.Property<decimal?>("GiaVon")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gia_von");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("longtext")
                        .HasColumnName("hinh_anh");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isDeleted");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("ma_danh_muc");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("TenMon")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ten_mon");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai")
                        .HasDefaultValueSql("'con_ban'");

                    b.HasKey("MaMon")
                        .HasName("PRIMARY");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("mon_an", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .HasColumnType("longtext")
                        .HasColumnName("ho_ten");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaVaiTro")
                        .HasColumnType("int")
                        .HasColumnName("ma_vai_tro");

                    b.Property<string>("MatKhau")
                        .HasColumnType("longtext")
                        .HasColumnName("mat_khau");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("OtpCode")
                        .HasColumnType("longtext")
                        .HasColumnName("otp_code");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("otp_expiry");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaNguoiDung")
                        .HasName("PRIMARY");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("nguoi_dung", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.PhieuKho", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phieu");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("LoaiPhieu")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("loai_phieu");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<decimal?>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien");

                    b.HasKey("MaPhieu")
                        .HasName("PRIMARY");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("phieu_kho", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.QuangCao", b =>
                {
                    b.Property<int>("MaQuangCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_quang_cao");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("longtext")
                        .HasColumnName("hinh_anh");

                    b.Property<bool>("KichHoat")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("kich_hoat");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("ma_danh_muc");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("int")
                        .HasColumnName("phan_tram_giam");

                    b.Property<string>("TieuDe")
                        .HasColumnType("longtext")
                        .HasColumnName("tieu_de");

                    b.HasKey("MaQuangCao")
                        .HasName("PRIMARY");

                    b.ToTable("quang_cao", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.QuyTacThoiGian", b =>
                {
                    b.Property<int>("MaQuyTac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Buoi")
                        .HasColumnType("longtext");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int?>("MaDanhMucNavigationMaDanhMuc")
                        .HasColumnType("int");

                    b.HasKey("MaQuyTac")
                        .HasName("PRIMARY");

                    b.HasIndex("MaDanhMucNavigationMaDanhMuc");

                    b.ToTable("quy_tac_thoi_gian", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenQuyen")
                        .HasColumnType("longtext");

                    b.HasKey("MaQuyen")
                        .HasName("PRIMARY");

                    b.ToTable("quyen", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_thanh_toan");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_don_hang");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_thanh_toan");

                    b.Property<string>("PhuongThuc")
                        .HasColumnType("longtext")
                        .HasColumnName("phuong_thuc");

                    b.Property<double>("SoTien")
                        .HasColumnType("double")
                        .HasColumnName("so_tien");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaThanhToan")
                        .HasName("PRIMARY");

                    b.HasIndex("MaDonHang");

                    b.ToTable("thanh_toan", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.ThoiTiet", b =>
                {
                    b.Property<int>("MaThoiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Loai")
                        .HasColumnType("longtext");

                    b.Property<float?>("NhietDo")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MaThoiTiet")
                        .HasName("PRIMARY");

                    b.ToTable("thoi_tiet", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("DaDoc")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDungNavigationMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("longtext");

                    b.HasKey("MaThongBao")
                        .HasName("PRIMARY");

                    b.HasIndex("MaNguoiDungNavigationMaNguoiDung");

                    b.ToTable("thong_bao", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenVaiTro")
                        .HasColumnType("longtext");

                    b.HasKey("MaVaiTro")
                        .HasName("PRIMARY");

                    b.ToTable("vai_tro", (string)null);
                });

            modelBuilder.Entity("AnFoodAPI.Models.Voucher", b =>
                {
                    b.Property<int>("MaVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_voucher");

                    b.Property<decimal>("DonToiThieu")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("don_toi_thieu");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("gia_tri_giam");

                    b.Property<decimal>("GiamToiDa")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("giam_toi_da");

                    b.Property<string>("LoaiGiamGia")
                        .HasColumnType("longtext")
                        .HasColumnName("loai_giam_gia");

                    b.Property<string>("MaCode")
                        .HasColumnType("longtext")
                        .HasColumnName("ma_code");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaVoucher");

                    b.ToTable("voucher");
                });

            modelBuilder.Entity("AnFoodAPI.Models.YeuThich", b =>
                {
                    b.Property<int>("MaYeuThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_yeu_thich");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("ma_mon");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("MaYeuThich")
                        .HasName("PRIMARY");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("yeu_thich", (string)null);
                });

            modelBuilder.Entity("QuyenVaiTro", b =>
                {
                    b.Property<int>("MaQuyensMaQuyen")
                        .HasColumnType("int");

                    b.Property<int>("MaVaiTrosMaVaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaQuyensMaQuyen", "MaVaiTrosMaVaiTro");

                    b.HasIndex("MaVaiTrosMaVaiTro");

                    b.ToTable("QuyenVaiTro");
                });

            modelBuilder.Entity("AnFoodAPI.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("AnFoodAPI.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang");

                    b.HasOne("AnFoodAPI.Models.MonAn", "MonAn")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaMon");

                    b.Navigation("DonHang");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("AnFoodAPI.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("AnFoodAPI.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang");

                    b.HasOne("AnFoodAPI.Models.MonAn", "MonAn")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaMon");

                    b.Navigation("GioHang");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("AnFoodAPI.Models.ChiTietKho", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", "MaMonNavigation")
                        .WithMany()
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.ChiTietPhieuKho", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", "MaMonNavigation")
                        .WithMany()
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnFoodAPI.Models.PhieuKho", "MaPhieuNavigation")
                        .WithMany("ChiTietPhieuKhos")
                        .HasForeignKey("MaPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaPhieuNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.DanhGia", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", null)
                        .WithMany("DanhGia")
                        .HasForeignKey("MaMon")
                        .IsRequired();

                    b.HasOne("AnFoodAPI.Models.NguoiDung", null)
                        .WithMany("DanhGia")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired();
                });

            modelBuilder.Entity("AnFoodAPI.Models.DiaChiGiaoHang", b =>
                {
                    b.HasOne("AnFoodAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DiaChiGiaoHangs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.DonHang", b =>
                {
                    b.HasOne("AnFoodAPI.Models.DiaChiGiaoHang", "DiaChiGiaoHangNavigation")
                        .WithMany()
                        .HasForeignKey("MaDiaChi");

                    b.HasOne("AnFoodAPI.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNguoiDung");

                    b.Navigation("DiaChiGiaoHangNavigation");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("AnFoodAPI.Models.GioHang", b =>
                {
                    b.HasOne("AnFoodAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaNguoiDung");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.GoiYAi", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", "MaMonNavigation")
                        .WithMany("GoiYAis")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_GoiY_MonAn");

                    b.HasOne("AnFoodAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("GoiYAis")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_GoiY_NguoiDung");

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.HanhViNguoiDung", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", "MaMonNavigation")
                        .WithMany("HanhViNguoiDungs")
                        .HasForeignKey("MaMon")
                        .HasConstraintName("FK_HanhVi_MonAn");

                    b.HasOne("AnFoodAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("HanhViNguoiDungs")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK_HanhVi_NguoiDung");

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.HinhAnhMonAn", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", "MonAn")
                        .WithMany("HinhAnhMonAns")
                        .HasForeignKey("MaMon");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("AnFoodAPI.Models.LichSuKho", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("AnFoodAPI.Models.LichSuTrangThaiDonHang", b =>
                {
                    b.HasOne("AnFoodAPI.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("LichSuTrangThaiDonHangs")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_LichSu_DonHang");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.MonAn", b =>
                {
                    b.HasOne("AnFoodAPI.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("MonAns")
                        .HasForeignKey("MaDanhMuc")
                        .HasConstraintName("mon_an_ibfk_1");

                    b.Navigation("MaDanhMucNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.NguoiDung", b =>
                {
                    b.HasOne("AnFoodAPI.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.PhieuKho", b =>
                {
                    b.HasOne("AnFoodAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.QuyTacThoiGian", b =>
                {
                    b.HasOne("AnFoodAPI.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("QuyTacThoiGians")
                        .HasForeignKey("MaDanhMucNavigationMaDanhMuc");

                    b.Navigation("MaDanhMucNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.ThanhToan", b =>
                {
                    b.HasOne("AnFoodAPI.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.ThongBao", b =>
                {
                    b.HasOne("AnFoodAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaNguoiDungNavigationMaNguoiDung");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("AnFoodAPI.Models.YeuThich", b =>
                {
                    b.HasOne("AnFoodAPI.Models.MonAn", "MaMonNavigation")
                        .WithMany("YeuThiches")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_YeuThich_MonAn");

                    b.HasOne("AnFoodAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("YeuThiches")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_YeuThich_NguoiDung");

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("QuyenVaiTro", b =>
                {
                    b.HasOne("AnFoodAPI.Models.Quyen", null)
                        .WithMany()
                        .HasForeignKey("MaQuyensMaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnFoodAPI.Models.VaiTro", null)
                        .WithMany()
                        .HasForeignKey("MaVaiTrosMaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnFoodAPI.Models.DanhMuc", b =>
                {
                    b.Navigation("MonAns");

                    b.Navigation("QuyTacThoiGians");
                });

            modelBuilder.Entity("AnFoodAPI.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("LichSuTrangThaiDonHangs");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("AnFoodAPI.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("AnFoodAPI.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("DanhGia");

                    b.Navigation("GoiYAis");

                    b.Navigation("HanhViNguoiDungs");

                    b.Navigation("HinhAnhMonAns");

                    b.Navigation("YeuThiches");
                });

            modelBuilder.Entity("AnFoodAPI.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("DiaChiGiaoHangs");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");

                    b.Navigation("GoiYAis");

                    b.Navigation("HanhViNguoiDungs");

                    b.Navigation("ThongBaos");

                    b.Navigation("YeuThiches");
                });

            modelBuilder.Entity("AnFoodAPI.Models.PhieuKho", b =>
                {
                    b.Navigation("ChiTietPhieuKhos");
                });

            modelBuilder.Entity("AnFoodAPI.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
